apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-microservice
  template:
    metadata:
      labels:
        app: aggregator-microservice
    spec:
      containers:
        - name: aggregator-application
          image: fouadkada/aggregator
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator
spec:
  type: ClusterIP
  selector:
    app: aggregator-microservice
  ports:
    - port: 3000

